### PR TITLE
Fix x show transition overlap

### LINKED ISSUE #533: Might be an Alpine Performance bug on `x-show` with transition
Tricky one, 
https://codepen.io/muzafferdede/pen/XWmLKJx

Screencast:
https://gofile.io/d/0bqt5t

When there is an element with any attribute in `x-show` element, things gets weird. 

In this example: 
Try to click on toggle button quickly multiple times. You will end up with half way done transition. `open` is `true` but transition is not completed. 

Once you remove `id` on inner element, things are fine. So i guess at some point Alpine doesn't has enough time to complete walking on dom and skip some tasks?

### PR DESCRIPTION
**Pull request by muzafferdede**
Fixes #533 (tested) |  #170 (tested, need more test) | #156 (partly tested, need more test) | `you tell me`

I have to refactor transition to achieve this solution. So there is a #542 Refactored Transition PR  of this PR which has same solution + refactored transitions to let transitions has its own space so it will be easier to work on it. (it was really hard to work on existing transition code). I have explained much more on #542 since they serve almost same purpose.  

This fix is quite self explanatory. I assigned few variables to check transitions and make sure and control how they are rendered.

By this, quick clicks overlapping transitions and wrong state of display issues will be fixed. There is also a test called `remaining transitions forced to complete if they exists` which tests this bug.

Let me know if there is any room to improve. Huge thanks @SimoTod and @HugoDF for their comments. .5 x more thanks to @SimoTod for bearing with me :).

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -397,14 +398,29 @@ export function transition(el, stages) {
...
+                if(el.__x_transition_timer){
+                    clearTimeout(el.__x_transition_timer)
+                }
+            }
+
+            el.__x_transition_timer = setTimeout(() => {
+                // We only want to run remaining transitions in the end if they exists
+                if (el.__x_transition_remaining) {
+                    el.__x_transition_remaining()
+                }
```
Comment (SimoTod) [inline src/utils.js:423]: I'd really like to use the once function from VUE here. This feels a bit clumsy somehow. It's like we are trying to clear as many variables as possible to make sure the timeout doesn't run.
I'm almost sure we can get the same result with
```
el.__x_transition_remaining = once(() => {
    stages.hide()

    // Adding an "isConnected" check, in case the callback
    // removed the element from the DOM.
    if (el.isConnected) {
        stages.cleanup()
    }

     // Safe to remove transition from el since it is completed
     delete el.__x_transition_remaining
})

setTimeout(el.__x_transition_remaining, duration);
```

File: src/directives/show.js [hunk 2]
```diff
@@ -1,6 +1,11 @@
 import { transitionIn, transitionOut } from '../utils'
 
 export function handleShowDirective(component, el, value, modifiers, initialUpdate = false) {
+    // Resolve any previous pending transitions before starting a new one
```
Comment (SimoTod) [inline src/directives/show.js:4]: is it relevant only for show? transitions are applied to x-if as well.

File: test/transition.spec.js [hunk 3]
```diff
@@ -620,3 +620,91 @@ test('x-transition supports css animation', async () => {
     )
     expect(document.querySelector('span').classList.contains('animation-leave')).toEqual(false)
 })
+
+test('remaining transitions forced to complete if they exists', async () => {
```
Comment (SimoTod) [inline test/transition.spec.js:624]: I run the same test against master and it did not fail. It seems a bit complex, is it supposed to test this feature?

File: src/directives/show.js [hunk 4]
```diff
@@ -26,9 +31,14 @@ export function handleShowDirective(component, el, value, modifiers, initialUpda
         if (! value) {
             if ( el.style.display !== 'none' ) {
                 transitionOut(el, () => {
-                    resolve(() => {
+                    // If previous transitions still there, don't use resolve
+                    if ( el.__x_transition_remaining ) {
```
[the remark this answers is not in the document]
Comment (muzafferdede) [reply src/directives/show.js:36]: As i said at #542 if value did not change but if there is a remaining transition, we should not use resolve.

File: src/utils.js (hunk 1 above)
Comment (muzafferdede) [reply src/utils.js]: Good news, i finally did figure out how to implement the way you mentioned. Good call @SimoTod. We are 1 variable less now :)

File: test/transition.spec.js (hunk 3 above)
Comment (muzafferdede) [reply test/transition.spec.js:624]: Fixed by improving the test

File: src/directives/show.js (hunk 2 above)
Comment (muzafferdede) [reply src/directives/show.js]: As i said in #542 we can run `el.transition_remaning()` any time if we need to clear transitions.

File: src/utils.js [hunk 5]
```diff
@@ -397,14 +398,29 @@ export function transition(el, stages) {
         requestAnimationFrame(() => {
             stages.end()
 
-            setTimeout(() => {
+            // Asign current transition to el in case we need to force it
```
[the remark this answers is not in the document]
Comment (muzafferdede) [reply src/utils.js:401]: Thanks, should be fine with yours :)

**Comment by muzafferdede** [comment]
Fixed by assigning `el.transition_last_value` at initial.
