### PR TITLE
Fix `x-sort` crash when container has a `<template>` with no `.content`

### LINKED ISSUE #2578: [PRO] FluxUI chart breaks inside wire:sort without wire:sort:handle
### Flux version

v2.13.2

### Livewire version

v4.2.4

### Tailwind version

v4.2.2

### Browser and Operating System

Firefox on Arch Linux

### What is the problem?

When a `flux:chart` is placed inside a `wire:sort:item` without a `wire:sort:handle` the dragging to reorder items stops working and a TypeError is thrown in the browser console.

```
Uncaught TypeError: can't access property "querySelector", tmpl.content is undefined
```

### Code snippets to replicate the problem

```blade
<?php

use Illuminate\Support\Collection;
use Livewire\Component;

new class extends Component {
    public array $tasks = [
        [
            'id' => 1,
            'title' => "Title 1",
        ],[
            'id' => 2,
            'title' => "Title 2",
        ],[
            'id' => 3,
            'title' => "Title 3",
        ],
    ];

    public function handleSort($id, $position): void
    {
        dump($id, $position);
    }
};
?>

<div>
    <div class="grid grid-cols-3 gap-4" wire:sort="handleSort">
        @foreach ($tasks as $task)
            <flux:card class="overflow-hidden min-w-[12rem]" wire:key="{{ $task['id'] }}" wire:sort:item="{{ $task['id'] }}">
                <flux:text>Revenue</flux:text>
                <flux:heading size="xl" class="mt-2 tabular-nums">$12,345 {{ $task['title'] }}</flux:heading>
                <flux:chart class="-mx-8 -mb-8 h-[3rem]" :value="[10, 12, 11, 13, 15, 14, 16, 18, 17, 19, 21, 20]">
                    <flux:chart.svg gutter="0">
                        <flux:chart.line class="text-sky-200 dark:text-sky-400" />
                        <flux:chart.area class="text-sky-100 dark:text-sky-400/30" />
                    </flux:chart.svg>
                </flux:chart>
            </flux:card>
        @endforeach
    </div>
</div>
```

### Screenshots/ screen recordings of the problem

Image

### How do you expect it to work?

No console errors. Items are draggable regardless of whether a flux:chart is present inside the wire:sort:item.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

### PR DESCRIPTION
**Pull request by joshhanley**
# The Scenario

Placing a `flux:chart` inside a `wire:sort:item` (with no `wire:sort:handle`) breaks drag-to-reorder and throws in the console:

Screenshot 2026-04-21 at 08 49 37AM@2x

```blade
<div wire:sort="handleSort">
    @foreach ($tasks as $task)
        <flux:card wire:key="{{ $task['id'] }}" wire:sort:item="{{ $task['id'] }}">
            <flux:chart :value="[10, 12, 11, 13, 15]">
                <flux:chart.svg>
                    <flux:chart.line />
                </flux:chart.svg>
            </flux:chart>
        </flux:card>
    @endforeach
</div>
```

# The Problem

`x-sort` auto-detects whether the sort container uses drag handles. If no handle element is found directly, it scans nested `<template>` elements for one:

```js
useHandles: !! el.querySelector(handleSelector)
    || Array.from(el.querySelectorAll('template')).some(tmpl => tmpl.content.querySelector(handleSelector)),
```

`querySelectorAll('template')` matches every element with tag name `template` regardless of namespace, but `.content` only exists on `HTMLTemplateElement`. Flux's chart hydrates its SVG from an HTML `<template>` and the hydrated `<svg>` contains nested `<template>` elements that were parsed in the SVG namespace, so they're `SVGElement` instances with no `.content` property. The unconditional `.querySelector` call on `tmpl.content` throws.

# The Solution

Guard the property access with optional chaining so non-`HTMLTemplateElement` matches are skipped:

```js
|| Array.from(el.querySelectorAll('template')).some(tmpl => tmpl.content?.querySelector(handleSelector)),
```

Screenshot 2026-04-21 at 08 50 09AM

Fixes livewire/flux#2578

### CODE REVIEW

File: packages/sort/src/index.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export default function (Alpine) {
         let preferences = {
             hideGhost: ! modifiers.includes('ghost'),
             useHandles: !! el.querySelector(handleSelector)
-                || Array.from(el.querySelectorAll('template')).some(tmpl => tmpl.content.querySelector(handleSelector)),
+                || Array.from(el.querySelectorAll('template')).some(tmpl => tmpl.content?.querySelector(handleSelector)),
```
Comment (ekwoka) [inline packages/sort/src/index.js]:
```suggestion
                || Array.from(el.querySelectorAll('template:not(svg template)')).some(tmpl => tmpl.content.querySelector(handleSelector)),
```

I think would also work to just handle it at the selector level

**Review by ekwoka — APPROVED** [review]

File: packages/sort/src/index.js (hunk 1 above)
Comment (joshhanley) [reply packages/sort/src/index.js]: Yeah good idea. I think we'll keep the `?` too just incase.

```suggestion
                || Array.from(el.querySelectorAll('template:not(svg template)')).some(tmpl => tmpl.content?.querySelector(handleSelector)),
```
